### ISSUE TITLE
getvarcol for varying shapes 

### ISSUE THREAD

**Issue by smasoka** [SpheMakh/msutils#31]
Testing BDA with CARACal (`obsconf`) I run into

```bash
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 73, in <module>
#     run_func(**_args)
#   File "/usr/local/lib/python3.6/dist-packages/MSUtils/msutils.py", line 112, in summary
#     info[key][name] = _tab.getcol(name).tolist()
#   File "/usr/local/lib/python3.6/dist-packages/casacore/tables/table.py", line 1032, in getcol
#     return self._getcol(columnname, startrow, nrow, rowincr)
# RuntimeError: ArrayColumn::getColumn cannot be done for column CHAN_FREQ; the array shapes vary: Table array conformance error
```

CHAN_FREQ shape varies, so we might need to workshop [`getcol`](https://casa.nrao.edu/docs/CasaRef/table.getcol.html)  versus [`getvarcol`](https://casa.nrao.edu/docs/CasaRef/table.getvarcol.html)  which addresses this limitation by returning the values as a record instead of an array?

**Comment by smasoka** [comment]
Something like this maybe ?
```python
for name in colnames:
    if _tab.isvarcol(name):
        info[key][name] = [lst[0].tolist() for lst in list(_tab.getvarcol(name).values())]
    else:
        try:
            info[key][name] = _tab.getcol(name).tolist()
        except AttributeError:
            info[key][name] = _tab.getcol(name)
```
not sure if that will break anything else though
